export const christmasQuotes = [
  "Christmas magic is silent. You don't hear it — you feel it. ✨",
  'May your days be merry and bright! 🎄',
  'The best way to spread Christmas cheer is singing loud for all to hear! 🎶',
  'Joy is the true gift of Christmas. 🎁',
  'Warm hearts make the coldest winter glow. ❄️❤️',
  'Believe in the magic of Christmas. ✨',
  'May your home be filled with peace, love, and cookies. 🍪',
  'Christmas is not a season. It’s a feeling. 🎄✨',
  'Gifts of time and love are surely the basic ingredients of a truly merry Christmas. ❤️',
  'May the spirit of Christmas warm your heart all year long. 🎁',
  'Sleigh bells ring, are you listening? 🔔❄️',
  'Christmas waves a magic wand over this world. 🎄',
  'All roads lead home for the holidays. 🏠❤️',
  "Let your heart be light — it's Christmas! ✨",
  'A little Christmas magic can take you a long way. ✨',
  'Christmas lights make everything brighter. 🌟',
  'Happiness is a warm cup of cocoa at Christmas. ☕❄️',
  'May your stocking overflow with joy. 🧦🎁',
  'Peace on Earth begins with a smile. 😊🌍',
  'It’s not what’s under the tree that matters, it’s who’s around it. 🎄❤️',
  'Christmas is the day that holds all time together. ⏳✨',
  'Let love be your gift this Christmas. 🎁❤️',
  'A cozy heart makes the best Christmas home. 🏠✨',
  'Cookies, cocoa, and Christmas cheer — the holy trinity! 🍪☕🎄',
  'Every snowflake brings a message of joy. ❄️✨',
  'Christmas is sweeter with the ones you love. ❤️🎄',
  'Keep calm and jingle all the way. 🔔😄',
  'Joy multiplies when shared — especially at Christmas! 🎁✨',
  'Santa believes in you. 🌟🎅',
  'May the season wrap you in warmth. 🧣❄️',
  'Christmas is love wrapped in sparkles. ✨❤️',
  'A joyful heart is the best Christmas decoration. 🎄✨',
  'May your Christmas be filled with laughter and light. 😂🌟',
  'Santa’s sleigh runs on joy — fuel up! 🎅✨',
  'Snowflakes are kisses from winter. ❄️😘',
  'Christmas is a hug wrapped in glitter. ✨🤗',
  'Wishing you magic, wonder, and peppermint joy. 🍬✨',
  'Let kindness be your Christmas gift to the world. 🎁❤️',
  'Hot cocoa + friends = the perfect Christmas recipe. ☕🎄',
  'May your heart feel as light as falling snow. ❄️❤️',
  'Sparkle like Christmas lights tonight. ✨🌟',
  'A warm heart melts winter cold. ❤️❄️',
  'May the melody of Christmas fill your soul. 🎶✨',
  'Christmas is the sparkle of the heart. 💖🌟',
  'Every tradition tells a story — cherish them. 🎄📖',
  'The greatest gift of Christmas is presence, not presents. ❤️',
  'Christmas is love wrapped in ribbons. 🎁❤️',
  'Let the spirit of Christmas lift your spirit too. 🎄✨',
  'Winter nights are brighter with Christmas lights. 🌟❄️',
  'May your holiday glow be merry and bright! ✨🎄',
  'Snowflakes remind us that each moment can sparkle. ❄️✨',
  'The holidays are a season of joy, not stress. Breathe. ❤️',
  'Magic begins the moment you believe. ✨🎄',
  'Santa’s favorite gift? A happy heart. ❤️🎅',
  'Christmas is a gentle reminder to slow down and savor joy. 🌟',
  'A warm blanket and Christmas music fixes everything. 🧣🎶',
  'Be the Christmas miracle someone needs. 🎄❤️',
  'Candy canes and cozy nights = Christmas bliss. 🍬✨',
  'Your smile is your holiday sparkle. ✨😊',
  'May your winter be filled with warm moments. ❄️❤️',
  'The real sparkle of Christmas is love. ✨❤️',
  'Let every twinkling light remind you of hope. 🌟🎄',
  'A grateful heart feels like Christmas. ❤️✨',
  'Christmas is joy wrapped in memories. 🎄💭',
  'May magic track you down wherever you go. ✨🎅',
  'Wishing you peace, love, and twinkling lights. 🌟❤️',
  'The world feels softer at Christmas. ❄️🌍',
  'May you find wonder in the smallest moments. ✨🎄',
  'Wrap yourself in the warmth of Christmas cheer. 🧣❤️',
  'Snow outside, warmth inside. ❄️🏠',
  'Believe. It is the magic word of Christmas. ✨',
  'You’re never too old for Christmas wonder. 🎄✨',
  'Let the season sprinkle joy into your days. ✨❤️',
  'Winter nights shine brighter with hope. 🌟❄️',
  'Christmas is best when shared with hearts you love. ❤️🎄',
  'Stars shine brighter in December. ✨🌌',
  'Carols turn moments into memories. 🎶❤️',
  'Give more hugs — it’s Christmas. 🤗🎄',
  'May love wrap around you like a warm blanket. ❤️🧣',
  'A little sparkle goes a long way. ✨🎄',
  'Jingle in your step, joy in your heart! 🔔✨',
  'May every wish you whisper find its way to the North Pole. 🎅✨',
  'Toasty socks and Christmas talks — the best combo. 🧦❤️',
  'Let this season remind you how blessed you are. 🎄✨',
  'Even the simplest Christmas can feel magical. ✨❤️',
  'The heart of Christmas is giving. 🎁❤️',
  'Snowy days are made for magic. ❄️✨',
  'Let joy fall like snow around you. ❄️❤️',
  'You deserve a Christmas full of light. ✨🎄',
  'May your heart shimmer with gratitude. 💖✨',
  'The North Pole called — they said you’re amazing. 🎅✨',
  'Be someone’s Christmas cheer today. ❤️🎄',
  'Where there is love, it feels like Christmas. ❤️✨',
  'Christmas isn’t a date; it’s a feeling we create. 🎄💫',
  'Celebrate the little miracles. ✨❤️',
  'Even one light defeats darkness — shine bright. 🌟',
  'Let your soul sparkle like a Christmas tree. 🎄✨',
  'Peppermint air, twinkling lights — Christmas is near! 🍬✨',
  'A joyful heart is a Christmas blessing. ❤️🎄',
  'Every act of kindness is Christmas in motion. 🎁❤️',
  'Nothing glows brighter than a grateful heart. ✨',
  'Warm wishes travel far — send yours freely. ❤️',
  'Happiness feels like home during Christmas. 🏠✨',
  'Let every moment glitter with joy. ✨🎄',
  'Your presence is a gift — don’t forget it. 🎁❤️',
  'Little joys make the biggest Christmas memories. 🎄✨',
  'Cocoa cures winter blues. ☕❄️',
  'Believe in magic — it believes in you. ✨🎄',
  'Even snowflakes know how to dance. ❄️💃',
  'Christmas begins with kindness. ❤️🎄',
  'A soft snowfall feels like a holiday poem. ❄️📖',
  'The world sparkles more this time of year. ✨🌍',
  'May your heart be light as tinsel. 🎄✨',
  'May peace wrap you like a warm scarf. 🧣❤️',
  'Love is the melody of Christmas. 🎶❤️',
  'Let your inner child out — it’s Christmas! 🎄✨',
  'A glowing tree makes the darkest night warm. 🌟🎄',
  'The joy you give comes back to you. ✨❤️',
  'Magic is real; you just need to notice it. 🎄✨',
  'Let hope be your winter flame. 🕯️❄️',
  'The season is short — make it sweet. 🍬✨',
  'Snowflakes whisper winter secrets. ❄️✨',
  'May your Christmas sparkle with new memories. ✨🎄',
  'Let love fill the spaces gifts can’t reach. ❤️',
  'Christmas is a warm hug to the soul. 🤗✨',
  'Be merry. Be bright. Be you. ✨🎄',
  'The tree isn’t the only thing that should twinkle. ✨🙂',
  'Peace begins where expectation ends. ❤️✨',
  'You bring your own magic to Christmas. 🎄✨',
  'This season, choose joy on purpose. ✨❤️',
  'The holiday glow hits different. ✨🌟',
  'May wonder follow you everywhere. ✨🎄',
  'Even the coldest nights can’t freeze a warm heart. ❄️❤️',
  'Christmas is a reminder that light always returns. 🌟✨',
  'The season feels brighter with you in it. ✨❤️',
  'Let every twinkling light remind you to shine. 🌟🎄',
  'Your joy is contagious — spread it. ✨😄',
  'Warm cocoa, warm hearts. ☕❤️',
  'May your winter sparkle with kindness. ✨❄️',
  'Hope shines brightest in December. 🌟✨',
  'Celebrate love — it’s the true Christmas gift. ❤️🎁',
  'Let your heart feel full this season. ❤️🎄',
  'The best Christmas gift is a peaceful mind. 🌟',
  'May your joy overflow like Christmas lights. ✨🎄',
  'Kind words are the ornaments of the soul. ✨❤️',
  'The magic you seek is already inside you. 🎄✨',
  'May your Christmas be as sweet as candy canes. 🍬✨',
  'Winter nights were made for soft thoughts. ❄️💭',
  'The stars are brighter on Christmas Eve. ✨🌌',
  'Let joy be your winter anthem. 🎶❤️',
  'Christmas is a warm whisper of hope. ✨🎄',
  'Wrap your heart in gratitude today. ❤️🎁',
  'Even a tiny sparkle can change everything. ✨',
  'Be gentle with yourself — it’s Christmas. ❤️🎄',
  'Let your heart glow like December lights. ✨🌟',
  'Celebrate love loudly this season. ❤️🎄',
  'Magic is found in the smallest Christmas moments. ✨❄️',
  'May your season be cozy and full of wonder. ✨🧣',
  'Christmas is joy in its purest form. 🎄✨',
  'Never stop believing in magic. ✨🎄',
  'Let your joy snowball this season. ❄️😄',
  'Love is always the brightest ornament. ❤️🎄',
  'Snow outside, warmth inside — perfect balance. ❄️🏠',
  'May your heart be merry and your days magical. ✨🎄',
  'Christmas teaches us to pause and appreciate. ❤️✨',
  'Your light matters. Keep shining. 🌟🎄',
  'The world needs your Christmas spirit. ✨❤️',
  'Hope is the greatest holiday tradition. 🌟🎄',
  'A cheerful heart makes winter feel warm. ❤️❄️',
  'Keep your soul wrapped in joy. 🎄✨'
]
