export const days = [
  { day: 1, name: 'Snowfall Landing', live: true },
  { day: 2, name: 'Santa Chat', live: true },
  { day: 3, name: 'Count Down', live: true },
  { day: 4, name: 'Christmas Quotes', live: true },
  { day: 5, name: 'Christmas Joke Generator', live: true },
  { day: 6, name: 'Elf Name Generator', live: true },
  { day: 7, name: 'Greeting Card Maker', live: true },
  { day: 8, name: 'Story Teller', live: true },
  { day: 9, name: 'Naughty or Nice Meter', live: true },
  { day: 10, name: 'Snowfall Customizer', live: true },
  { day: 11, name: 'Santa Tracker Animation', live: true },
  { day: 12, name: 'Christmas Move Recommender', live: false },
  { day: 13, name: 'Festive Playlist Generator', live: false },
  { day: 14, name: 'Virtual Snow Globe', live: false },
  { day: 15, name: 'Holiday Light Simulator', live: false },
  { day: 16, name: 'Christmas Trivia Game', live: false },
  { day: 17, name: 'Santa Tracker', live: false },
  { day: 18, name: 'Winter Wallpaper Generator', live: false },
  { day: 19, name: 'Holiday Countdown Timer', live: false },
  { day: 20, name: 'Christmas Card Sender', live: false },
  { day: 21, name: 'Festive Photo Booth', live: false },
  { day: 22, name: 'New Year Resolution Helper', live: false }
]
