export const days = [
  { day: 1, name: "Snowfall Landing", live: true },
  { day: 2, name: "Santa Chat", live: true },
  { day: 3, name: "Count Down", live: true },
  { day: 4, name: "Christmas Quotes", live: true },
  { day: 5, name: "Christmas Joke Generator", live: true },
  { day: 6, name: "Elf Name Generator", live: true },
  { day: 7, name: "Greeting Card Maker", live: true },
  { day: 8, name: "Story Teller", live: true },
  { day: 9, name: "Naughty or Nice Meter", live: true },
  { day: 10, name: "Snowfall Customizer", live: true },
  { day: 11, name: "Santa Tracker Animation", live: true },
  { day: 12, name: "Gift Recommendation Engine", live: true },
  { day: 13, name: "Christmas Music Player", live: true },
  { day: 14, name: "Christmas Tree Decorator", live: true },
  { day: 15, name: "Build-Your-Snowman Mini App", live: true },
  { day: 16, name: "Secret Santa Randomizer", live: false },
  { day: 17, name: "Christmas Quiz Game", live: false },
  { day: 18, name: "Holiday To-Do List", live: false },
  { day: 19, name: "Christmas Photo Filters", live: false },
  { day: 20, name: "Christmas Color Palette Generator", live: false },
  { day: 21, name: "Christmas E-Card Sharing", live: false },
  { day: 22, name: "Final Polish + Magic Reveal", live: false },
  { day: 23, name: "GRAND CHRISTMAS DAY POST", live: false }
];
